CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE security_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    locked BOOLEAN NOT NULL DEFAULT FALSE,
    auth_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE security_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE security_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE security_user_role (
    user_id BIGINT NOT NULL REFERENCES security_user(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES security_role(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE security_role_permission (
    role_id BIGINT NOT NULL REFERENCES security_role(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES security_permission(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE warehouse_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    code VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (warehouse_id, code)
);

CREATE TABLE security_user_warehouse_scope (
    user_id BIGINT NOT NULL REFERENCES security_user(id) ON DELETE CASCADE,
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id) ON DELETE CASCADE,
    scope_role VARCHAR(30) NOT NULL CHECK (scope_role IN ('VIEWER','OPERATOR','APPROVER','MANAGER')),
    PRIMARY KEY (user_id, warehouse_id)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    parent_id BIGINT REFERENCES category(id),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(80) NOT NULL UNIQUE,
    barcode VARCHAR(120) UNIQUE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES category(id),
    unit VARCHAR(30) NOT NULL DEFAULT 'UNIT',
    minimum_stock NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE product_supplier (
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    supplier_id BIGINT NOT NULL REFERENCES supplier(id) ON DELETE CASCADE,
    supplier_product_code VARCHAR(100),
    unit_cost NUMERIC(19,4) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    preferred BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (product_id, supplier_id)
);

CREATE TABLE inventory_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id),
    warehouse_location_id BIGINT NOT NULL REFERENCES warehouse_location(id),
    quantity NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    reserved_quantity NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (product_id, warehouse_location_id),
    CHECK (reserved_quantity <= quantity)
);

CREATE TABLE stock_movement (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_number VARCHAR(80) NOT NULL UNIQUE,
    movement_type VARCHAR(30) NOT NULL CHECK (movement_type IN ('RECEIPT','ISSUE','TRANSFER','ADJUSTMENT','RETURN')),
    status VARCHAR(30) NOT NULL CHECK (status IN ('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','CANCELLED')),
    source_warehouse_id BIGINT REFERENCES warehouse(id),
    target_warehouse_id BIGINT REFERENCES warehouse(id),
    external_reference VARCHAR(160),
    reason VARCHAR(500),
    created_by BIGINT NOT NULL REFERENCES security_user(id),
    approved_by BIGINT REFERENCES security_user(id),
    posted_by BIGINT REFERENCES security_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at TIMESTAMPTZ,
    posted_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CHECK (source_warehouse_id IS NOT NULL OR target_warehouse_id IS NOT NULL)
);

CREATE TABLE stock_movement_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id UUID NOT NULL REFERENCES stock_movement(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product(id),
    source_location_id BIGINT REFERENCES warehouse_location(id),
    target_location_id BIGINT REFERENCES warehouse_location(id),
    quantity NUMERIC(19,4) NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC(19,4) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    note VARCHAR(500)
);

CREATE TABLE stock_reservation (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_id BIGINT NOT NULL REFERENCES product(id),
    warehouse_location_id BIGINT NOT NULL REFERENCES warehouse_location(id),
    quantity NUMERIC(19,4) NOT NULL CHECK (quantity > 0),
    status VARCHAR(30) NOT NULL CHECK (status IN ('ACTIVE','FULFILLED','CANCELLED','EXPIRED')),
    reference VARCHAR(160),
    created_by BIGINT NOT NULL REFERENCES security_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ
);

CREATE TABLE purchase_order (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number VARCHAR(80) NOT NULL UNIQUE,
    supplier_id BIGINT NOT NULL REFERENCES supplier(id),
    target_warehouse_id BIGINT NOT NULL REFERENCES warehouse(id),
    status VARCHAR(30) NOT NULL CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
    created_by BIGINT NOT NULL REFERENCES security_user(id),
    approved_by BIGINT REFERENCES security_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approved_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE purchase_order_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id UUID NOT NULL REFERENCES purchase_order(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product(id),
    ordered_quantity NUMERIC(19,4) NOT NULL CHECK (ordered_quantity > 0),
    received_quantity NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
    unit_cost NUMERIC(19,4) CHECK (unit_cost IS NULL OR unit_cost >= 0),
    CHECK (received_quantity <= ordered_quantity)
);

CREATE TABLE auth_session (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES security_user(id) ON DELETE CASCADE,
    user_agent VARCHAR(500),
    ip_hash VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ
);

CREATE TABLE auth_refresh_token (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES auth_session(id) ON DELETE CASCADE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    parent_token_id UUID REFERENCES auth_refresh_token(id),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE contact_message (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(160) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'NEW' CHECK (status IN ('NEW','IN_PROGRESS','RESOLVED','SPAM')),
    assigned_to BIGINT REFERENCES security_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ
);

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES security_user(id),
    event_type VARCHAR(120) NOT NULL,
    entity_type VARCHAR(120) NOT NULL,
    entity_id VARCHAR(160),
    event_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE stock_movement_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id UUID,
    operation VARCHAR(10) NOT NULL,
    actor_user_id BIGINT,
    db_user VARCHAR(120) NOT NULL,
    old_row JSONB,
    new_row JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_inventory_balance_product ON inventory_balance(product_id);
CREATE INDEX idx_inventory_balance_location ON inventory_balance(warehouse_location_id);
CREATE INDEX idx_stock_movement_status ON stock_movement(status);
CREATE INDEX idx_stock_movement_created_at ON stock_movement(created_at DESC);
CREATE INDEX idx_audit_event_entity ON audit_event(entity_type, entity_id);
CREATE INDEX idx_audit_event_occurred_at ON audit_event(occurred_at DESC);
CREATE INDEX idx_refresh_session ON auth_refresh_token(session_id);
